; Char : 0x20  
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
; Char : 0x21 !
; planes 0 and 1
.byte $78,$78	;  ####   
.byte $78,$78	;  ####   
.byte $78,$78	;  ####   
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $00,$00	;         
.byte $30,$30	;   ##    
.byte $00,$00	;         
; planes 2 and 3
.byte $78,$78	;  ####   
.byte $78,$78	;  ####   
.byte $78,$78	;  ####   
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $00,$00	;         
.byte $30,$30	;   ##    
.byte $00,$00	;         
; Char : 0x22 "
; planes 0 and 1
.byte $34,$34	;   ## #  
.byte $34,$34	;   ## #  
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
; planes 2 and 3
.byte $34,$34	;   ## #  
.byte $34,$34	;   ## #  
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
; Char : 0x23 #
; planes 0 and 1
.byte $28,$28	;   # #   
.byte $7c,$7c	;  #####  
.byte $28,$28	;   # #   
.byte $28,$28	;   # #   
.byte $7c,$7c	;  #####  
.byte $28,$28	;   # #   
.byte $28,$28	;   # #   
.byte $00,$00	;         
; planes 2 and 3
.byte $28,$28	;   # #   
.byte $7c,$7c	;  #####  
.byte $28,$28	;   # #   
.byte $28,$28	;   # #   
.byte $7c,$7c	;  #####  
.byte $28,$28	;   # #   
.byte $28,$28	;   # #   
.byte $00,$00	;         
; Char : 0x24 $
; planes 0 and 1
.byte $10,$10	;    #    
.byte $7c,$7c	;  #####  
.byte $50,$50	;  # #    
.byte $7c,$7c	;  #####  
.byte $14,$14	;    # #  
.byte $7c,$7c	;  #####  
.byte $10,$10	;    #    
.byte $00,$00	;         
; planes 2 and 3
.byte $10,$10	;    #    
.byte $7c,$7c	;  #####  
.byte $50,$50	;  # #    
.byte $7c,$7c	;  #####  
.byte $14,$14	;    # #  
.byte $7c,$7c	;  #####  
.byte $10,$10	;    #    
.byte $00,$00	;         
; Char : 0x25 %
; planes 0 and 1
.byte $00,$00	;         
.byte $62,$62	;  ##   # 
.byte $64,$64	;  ##  #  
.byte $08,$08	;     #   
.byte $10,$10	;    #    
.byte $26,$26	;   #  ## 
.byte $46,$46	;  #   ## 
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $62,$62	;  ##   # 
.byte $64,$64	;  ##  #  
.byte $08,$08	;     #   
.byte $10,$10	;    #    
.byte $26,$26	;   #  ## 
.byte $46,$46	;  #   ## 
.byte $00,$00	;         
; Char : 0x26 &
; planes 0 and 1
.byte $00,$00	;         
.byte $38,$38	;   ###   
.byte $40,$40	;  #      
.byte $20,$20	;   #     
.byte $54,$54	;  # # #  
.byte $48,$48	;  #  #   
.byte $34,$34	;   ## #  
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $38,$38	;   ###   
.byte $40,$40	;  #      
.byte $20,$20	;   #     
.byte $54,$54	;  # # #  
.byte $48,$48	;  #  #   
.byte $34,$34	;   ## #  
.byte $00,$00	;         
; Char : 0x27 '
; planes 0 and 1
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $10,$10	;    #    
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
; planes 2 and 3
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $10,$10	;    #    
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
; Char : 0x28 (
; planes 0 and 1
.byte $08,$08	;     #   
.byte $10,$10	;    #    
.byte $20,$20	;   #     
.byte $20,$20	;   #     
.byte $20,$20	;   #     
.byte $10,$10	;    #    
.byte $08,$08	;     #   
.byte $00,$00	;         
; planes 2 and 3
.byte $08,$08	;     #   
.byte $10,$10	;    #    
.byte $20,$20	;   #     
.byte $20,$20	;   #     
.byte $20,$20	;   #     
.byte $10,$10	;    #    
.byte $08,$08	;     #   
.byte $00,$00	;         
; Char : 0x29 )
; planes 0 and 1
.byte $20,$20	;   #     
.byte $10,$10	;    #    
.byte $08,$08	;     #   
.byte $08,$08	;     #   
.byte $08,$08	;     #   
.byte $10,$10	;    #    
.byte $20,$20	;   #     
.byte $00,$00	;         
; planes 2 and 3
.byte $20,$20	;   #     
.byte $10,$10	;    #    
.byte $08,$08	;     #   
.byte $08,$08	;     #   
.byte $08,$08	;     #   
.byte $10,$10	;    #    
.byte $20,$20	;   #     
.byte $00,$00	;         
; Char : 0x2a *
; planes 0 and 1
.byte $92,$92	; #  #  # 
.byte $54,$54	;  # # #  
.byte $38,$38	;   ###   
.byte $fe,$fe	; ####### 
.byte $38,$38	;   ###   
.byte $54,$54	;  # # #  
.byte $92,$92	; #  #  # 
.byte $00,$00	;         
; planes 2 and 3
.byte $92,$92	; #  #  # 
.byte $54,$54	;  # # #  
.byte $38,$38	;   ###   
.byte $fe,$fe	; ####### 
.byte $38,$38	;   ###   
.byte $54,$54	;  # # #  
.byte $92,$92	; #  #  # 
.byte $00,$00	;         
; Char : 0x2b +
; planes 0 and 1
.byte $00,$00	;         
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $7c,$7c	;  #####  
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $00,$00	;         
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $7c,$7c	;  #####  
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $00,$00	;         
.byte $00,$00	;         
; Char : 0x2c ,
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $20,$20	;   #     
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $20,$20	;   #     
; Char : 0x2d -
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
; Char : 0x2e .
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $00,$00	;         
; Char : 0x2f /
; planes 0 and 1
.byte $02,$02	;       # 
.byte $06,$06	;      ## 
.byte $0c,$0c	;     ##  
.byte $18,$18	;    ##   
.byte $30,$30	;   ##    
.byte $e0,$e0	; ###     
.byte $c0,$c0	; ##      
.byte $00,$00	;         
; planes 2 and 3
.byte $02,$02	;       # 
.byte $06,$06	;      ## 
.byte $0c,$0c	;     ##  
.byte $18,$18	;    ##   
.byte $30,$30	;   ##    
.byte $e0,$e0	; ###     
.byte $c0,$c0	; ##      
.byte $00,$00	;         
; Char : 0x30 0
; planes 0 and 1
.byte $fe,$fe	; ####### 
.byte $c6,$c6	; ##   ## 
.byte $ce,$ce	; ##  ### 
.byte $da,$da	; ## ## # 
.byte $f2,$f2	; ####  # 
.byte $e2,$e2	; ###   # 
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; planes 2 and 3
.byte $fe,$fe	; ####### 
.byte $c6,$c6	; ##   ## 
.byte $ce,$ce	; ##  ### 
.byte $da,$da	; ## ## # 
.byte $f2,$f2	; ####  # 
.byte $e2,$e2	; ###   # 
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; Char : 0x31 1
; planes 0 and 1
.byte $30,$30	;   ##    
.byte $70,$70	;  ###    
.byte $b0,$b0	; # ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $fc,$fc	; ######  
.byte $00,$00	;         
; planes 2 and 3
.byte $30,$30	;   ##    
.byte $70,$70	;  ###    
.byte $b0,$b0	; # ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $fc,$fc	; ######  
.byte $00,$00	;         
; Char : 0x32 2
; planes 0 and 1
.byte $78,$78	;  ####   
.byte $84,$84	; #    #  
.byte $08,$08	;     #   
.byte $10,$10	;    #    
.byte $20,$20	;   #     
.byte $40,$40	;  #      
.byte $fc,$fc	; ######  
.byte $00,$00	;         
; planes 2 and 3
.byte $78,$78	;  ####   
.byte $84,$84	; #    #  
.byte $08,$08	;     #   
.byte $10,$10	;    #    
.byte $20,$20	;   #     
.byte $40,$40	;  #      
.byte $fc,$fc	; ######  
.byte $00,$00	;         
; Char : 0x33 3
; planes 0 and 1
.byte $78,$78	;  ####   
.byte $84,$84	; #    #  
.byte $04,$04	;      #  
.byte $3c,$3c	;   ####  
.byte $04,$04	;      #  
.byte $84,$84	; #    #  
.byte $78,$78	;  ####   
.byte $00,$00	;         
; planes 2 and 3
.byte $78,$78	;  ####   
.byte $84,$84	; #    #  
.byte $04,$04	;      #  
.byte $3c,$3c	;   ####  
.byte $04,$04	;      #  
.byte $84,$84	; #    #  
.byte $78,$78	;  ####   
.byte $00,$00	;         
; Char : 0x34 4
; planes 0 and 1
.byte $c4,$c4	; ##   #  
.byte $c4,$c4	; ##   #  
.byte $c4,$c4	; ##   #  
.byte $fc,$fc	; ######  
.byte $04,$04	;      #  
.byte $04,$04	;      #  
.byte $04,$04	;      #  
.byte $00,$00	;         
; planes 2 and 3
.byte $c4,$c4	; ##   #  
.byte $c4,$c4	; ##   #  
.byte $c4,$c4	; ##   #  
.byte $fc,$fc	; ######  
.byte $04,$04	;      #  
.byte $04,$04	;      #  
.byte $04,$04	;      #  
.byte $00,$00	;         
; Char : 0x35 5
; planes 0 and 1
.byte $fc,$fc	; ######  
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $f8,$f8	; #####   
.byte $04,$04	;      #  
.byte $04,$04	;      #  
.byte $f8,$f8	; #####   
.byte $00,$00	;         
; planes 2 and 3
.byte $fc,$fc	; ######  
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $f8,$f8	; #####   
.byte $04,$04	;      #  
.byte $04,$04	;      #  
.byte $f8,$f8	; #####   
.byte $00,$00	;         
; Char : 0x36 6
; planes 0 and 1
.byte $7c,$7c	;  #####  
.byte $c4,$c4	; ##   #  
.byte $c0,$c0	; ##      
.byte $f8,$f8	; #####   
.byte $c4,$c4	; ##   #  
.byte $c4,$c4	; ##   #  
.byte $f8,$f8	; #####   
.byte $00,$00	;         
; planes 2 and 3
.byte $7c,$7c	;  #####  
.byte $c4,$c4	; ##   #  
.byte $c0,$c0	; ##      
.byte $f8,$f8	; #####   
.byte $c4,$c4	; ##   #  
.byte $c4,$c4	; ##   #  
.byte $f8,$f8	; #####   
.byte $00,$00	;         
; Char : 0x37 7
; planes 0 and 1
.byte $fc,$fc	; ######  
.byte $84,$84	; #    #  
.byte $08,$08	;     #   
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $20,$20	;   #     
.byte $20,$20	;   #     
.byte $00,$00	;         
; planes 2 and 3
.byte $fc,$fc	; ######  
.byte $84,$84	; #    #  
.byte $08,$08	;     #   
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $20,$20	;   #     
.byte $20,$20	;   #     
.byte $00,$00	;         
; Char : 0x38 8
; planes 0 and 1
.byte $78,$78	;  ####   
.byte $c4,$c4	; ##   #  
.byte $c4,$c4	; ##   #  
.byte $78,$78	;  ####   
.byte $c4,$c4	; ##   #  
.byte $c4,$c4	; ##   #  
.byte $78,$78	;  ####   
.byte $00,$00	;         
; planes 2 and 3
.byte $78,$78	;  ####   
.byte $c4,$c4	; ##   #  
.byte $c4,$c4	; ##   #  
.byte $78,$78	;  ####   
.byte $c4,$c4	; ##   #  
.byte $c4,$c4	; ##   #  
.byte $78,$78	;  ####   
.byte $00,$00	;         
; Char : 0x39 9
; planes 0 and 1
.byte $7c,$7c	;  #####  
.byte $c4,$c4	; ##   #  
.byte $c4,$c4	; ##   #  
.byte $7c,$7c	;  #####  
.byte $04,$04	;      #  
.byte $04,$04	;      #  
.byte $04,$04	;      #  
.byte $00,$00	;         
; planes 2 and 3
.byte $7c,$7c	;  #####  
.byte $c4,$c4	; ##   #  
.byte $c4,$c4	; ##   #  
.byte $7c,$7c	;  #####  
.byte $04,$04	;      #  
.byte $04,$04	;      #  
.byte $04,$04	;      #  
.byte $00,$00	;         
; Char : 0x3a :
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $00,$00	;         
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $00,$00	;         
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $00,$00	;         
; Char : 0x3b ;
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $00,$00	;         
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $20,$20	;   #     
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $00,$00	;         
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $20,$20	;   #     
; Char : 0x3c <
; planes 0 and 1
.byte $18,$18	;    ##   
.byte $30,$30	;   ##    
.byte $60,$60	;  ##     
.byte $c0,$c0	; ##      
.byte $60,$60	;  ##     
.byte $30,$30	;   ##    
.byte $18,$18	;    ##   
.byte $00,$00	;         
; planes 2 and 3
.byte $18,$18	;    ##   
.byte $30,$30	;   ##    
.byte $60,$60	;  ##     
.byte $c0,$c0	; ##      
.byte $60,$60	;  ##     
.byte $30,$30	;   ##    
.byte $18,$18	;    ##   
.byte $00,$00	;         
; Char : 0x3d =
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
; Char : 0x3e >
; planes 0 and 1
.byte $c0,$c0	; ##      
.byte $60,$60	;  ##     
.byte $30,$30	;   ##    
.byte $18,$18	;    ##   
.byte $30,$30	;   ##    
.byte $60,$60	;  ##     
.byte $c0,$c0	; ##      
.byte $00,$00	;         
; planes 2 and 3
.byte $c0,$c0	; ##      
.byte $60,$60	;  ##     
.byte $30,$30	;   ##    
.byte $18,$18	;    ##   
.byte $30,$30	;   ##    
.byte $60,$60	;  ##     
.byte $c0,$c0	; ##      
.byte $00,$00	;         
; Char : 0x3f ?
; planes 0 and 1
.byte $78,$78	;  ####   
.byte $cc,$cc	; ##  ##  
.byte $98,$98	; #  ##   
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $00,$00	;         
.byte $30,$30	;   ##    
.byte $00,$00	;         
; planes 2 and 3
.byte $78,$78	;  ####   
.byte $cc,$cc	; ##  ##  
.byte $98,$98	; #  ##   
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $00,$00	;         
.byte $30,$30	;   ##    
.byte $00,$00	;         
; Char : 0x40 @
; planes 0 and 1
.byte $fc,$fc	; ######  
.byte $84,$84	; #    #  
.byte $bc,$bc	; # ####  
.byte $a4,$a4	; # #  #  
.byte $bc,$bc	; # ####  
.byte $80,$80	; #       
.byte $fc,$fc	; ######  
.byte $00,$00	;         
; planes 2 and 3
.byte $fc,$fc	; ######  
.byte $84,$84	; #    #  
.byte $bc,$bc	; # ####  
.byte $a4,$a4	; # #  #  
.byte $bc,$bc	; # ####  
.byte $80,$80	; #       
.byte $fc,$fc	; ######  
.byte $00,$00	;         
; Char : 0x41 A
; planes 0 and 1
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $00,$00	;         
; planes 2 and 3
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $00,$00	;         
; Char : 0x42 B
; planes 0 and 1
.byte $f8,$f8	; #####   
.byte $c8,$c8	; ##  #   
.byte $c8,$c8	; ##  #   
.byte $fc,$fc	; ######  
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fc,$fc	; ######  
.byte $00,$00	;         
; planes 2 and 3
.byte $f8,$f8	; #####   
.byte $c8,$c8	; ##  #   
.byte $c8,$c8	; ##  #   
.byte $fc,$fc	; ######  
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fc,$fc	; ######  
.byte $00,$00	;         
; Char : 0x43 C
; planes 0 and 1
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; planes 2 and 3
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; Char : 0x44 D
; planes 0 and 1
.byte $f8,$f8	; #####   
.byte $c4,$c4	; ##   #  
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fc,$fc	; ######  
.byte $00,$00	;         
; planes 2 and 3
.byte $f8,$f8	; #####   
.byte $c4,$c4	; ##   #  
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fc,$fc	; ######  
.byte $00,$00	;         
; Char : 0x45 E
; planes 0 and 1
.byte $fe,$fe	; ####### 
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $fe,$fe	; ####### 
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; planes 2 and 3
.byte $fe,$fe	; ####### 
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $fe,$fe	; ####### 
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; Char : 0x46 F
; planes 0 and 1
.byte $fe,$fe	; ####### 
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $fe,$fe	; ####### 
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $00,$00	;         
; planes 2 and 3
.byte $fe,$fe	; ####### 
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $fe,$fe	; ####### 
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $00,$00	;         
; Char : 0x47 G
; planes 0 and 1
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c0,$c0	; ##      
.byte $ce,$ce	; ##  ### 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; planes 2 and 3
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c0,$c0	; ##      
.byte $ce,$ce	; ##  ### 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; Char : 0x48 H
; planes 0 and 1
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $00,$00	;         
; planes 2 and 3
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $00,$00	;         
; Char : 0x49 I
; planes 0 and 1
.byte $fe,$fe	; ####### 
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; planes 2 and 3
.byte $fe,$fe	; ####### 
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; Char : 0x4a J
; planes 0 and 1
.byte $0e,$0e	;     ### 
.byte $02,$02	;       # 
.byte $02,$02	;       # 
.byte $02,$02	;       # 
.byte $c2,$c2	; ##    # 
.byte $64,$64	;  ##  #  
.byte $38,$38	;   ###   
.byte $00,$00	;         
; planes 2 and 3
.byte $0e,$0e	;     ### 
.byte $02,$02	;       # 
.byte $02,$02	;       # 
.byte $02,$02	;       # 
.byte $c2,$c2	; ##    # 
.byte $64,$64	;  ##  #  
.byte $38,$38	;   ###   
.byte $00,$00	;         
; Char : 0x4b K
; planes 0 and 1
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $cc,$cc	; ##  ##  
.byte $f0,$f0	; ####    
.byte $cc,$cc	; ##  ##  
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $00,$00	;         
; planes 2 and 3
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $cc,$cc	; ##  ##  
.byte $f0,$f0	; ####    
.byte $cc,$cc	; ##  ##  
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $00,$00	;         
; Char : 0x4c L
; planes 0 and 1
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; planes 2 and 3
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; Char : 0x4d M
; planes 0 and 1
.byte $c2,$c2	; ##    # 
.byte $e6,$e6	; ###  ## 
.byte $ee,$ee	; ### ### 
.byte $fa,$fa	; ##### # 
.byte $d2,$d2	; ## #  # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $00,$00	;         
; planes 2 and 3
.byte $c2,$c2	; ##    # 
.byte $e6,$e6	; ###  ## 
.byte $ee,$ee	; ### ### 
.byte $fa,$fa	; ##### # 
.byte $d2,$d2	; ## #  # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $00,$00	;         
; Char : 0x4e N
; planes 0 and 1
.byte $c2,$c2	; ##    # 
.byte $e2,$e2	; ###   # 
.byte $f2,$f2	; ####  # 
.byte $da,$da	; ## ## # 
.byte $ca,$ca	; ##  # # 
.byte $c6,$c6	; ##   ## 
.byte $c6,$c6	; ##   ## 
.byte $00,$00	;         
; planes 2 and 3
.byte $c2,$c2	; ##    # 
.byte $e2,$e2	; ###   # 
.byte $f2,$f2	; ####  # 
.byte $da,$da	; ## ## # 
.byte $ca,$ca	; ##  # # 
.byte $c6,$c6	; ##   ## 
.byte $c6,$c6	; ##   ## 
.byte $00,$00	;         
; Char : 0x4f O
; planes 0 and 1
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; planes 2 and 3
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; Char : 0x50 P
; planes 0 and 1
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fe,$fe	; ####### 
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $00,$00	;         
; planes 2 and 3
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fe,$fe	; ####### 
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $00,$00	;         
; Char : 0x51 Q
; planes 0 and 1
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $ca,$ca	; ##  # # 
.byte $c6,$c6	; ##   ## 
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; planes 2 and 3
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $ca,$ca	; ##  # # 
.byte $c6,$c6	; ##   ## 
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; Char : 0x52 R
; planes 0 and 1
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fe,$fe	; ####### 
.byte $c8,$c8	; ##  #   
.byte $c4,$c4	; ##   #  
.byte $c2,$c2	; ##    # 
.byte $00,$00	;         
; planes 2 and 3
.byte $fe,$fe	; ####### 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fe,$fe	; ####### 
.byte $c8,$c8	; ##  #   
.byte $c4,$c4	; ##   #  
.byte $c2,$c2	; ##    # 
.byte $00,$00	;         
; Char : 0x53 S
; planes 0 and 1
.byte $fe,$fe	; ####### 
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $fe,$fe	; ####### 
.byte $02,$02	;       # 
.byte $82,$82	; #     # 
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; planes 2 and 3
.byte $fe,$fe	; ####### 
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $fe,$fe	; ####### 
.byte $02,$02	;       # 
.byte $82,$82	; #     # 
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; Char : 0x54 T
; planes 0 and 1
.byte $fe,$fe	; ####### 
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $00,$00	;         
; planes 2 and 3
.byte $fe,$fe	; ####### 
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $00,$00	;         
; Char : 0x55 U
; planes 0 and 1
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; planes 2 and 3
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; Char : 0x56 V
; planes 0 and 1
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c4,$c4	; ##   #  
.byte $64,$64	;  ##  #  
.byte $68,$68	;  ## #   
.byte $38,$38	;   ###   
.byte $30,$30	;   ##    
.byte $00,$00	;         
; planes 2 and 3
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c4,$c4	; ##   #  
.byte $64,$64	;  ##  #  
.byte $68,$68	;  ## #   
.byte $38,$38	;   ###   
.byte $30,$30	;   ##    
.byte $00,$00	;         
; Char : 0x57 W
; planes 0 and 1
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $d2,$d2	; ## #  # 
.byte $f2,$f2	; ####  # 
.byte $fa,$fa	; ##### # 
.byte $c6,$c6	; ##   ## 
.byte $00,$00	;         
; planes 2 and 3
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $d2,$d2	; ## #  # 
.byte $f2,$f2	; ####  # 
.byte $fa,$fa	; ##### # 
.byte $c6,$c6	; ##   ## 
.byte $00,$00	;         
; Char : 0x58 X
; planes 0 and 1
.byte $c2,$c2	; ##    # 
.byte $c6,$c6	; ##   ## 
.byte $3c,$3c	;   ####  
.byte $18,$18	;    ##   
.byte $3c,$3c	;   ####  
.byte $c6,$c6	; ##   ## 
.byte $c2,$c2	; ##    # 
.byte $00,$00	;         
; planes 2 and 3
.byte $c2,$c2	; ##    # 
.byte $c6,$c6	; ##   ## 
.byte $3c,$3c	;   ####  
.byte $18,$18	;    ##   
.byte $3c,$3c	;   ####  
.byte $c6,$c6	; ##   ## 
.byte $c2,$c2	; ##    # 
.byte $00,$00	;         
; Char : 0x59 Y
; planes 0 and 1
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $64,$64	;  ##  #  
.byte $68,$68	;  ## #   
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $00,$00	;         
; planes 2 and 3
.byte $c2,$c2	; ##    # 
.byte $c2,$c2	; ##    # 
.byte $64,$64	;  ##  #  
.byte $68,$68	;  ## #   
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $30,$30	;   ##    
.byte $00,$00	;         
; Char : 0x5a Z
; planes 0 and 1
.byte $fe,$fe	; ####### 
.byte $04,$04	;      #  
.byte $08,$08	;     #   
.byte $30,$30	;   ##    
.byte $60,$60	;  ##     
.byte $c0,$c0	; ##      
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; planes 2 and 3
.byte $fe,$fe	; ####### 
.byte $04,$04	;      #  
.byte $08,$08	;     #   
.byte $30,$30	;   ##    
.byte $60,$60	;  ##     
.byte $c0,$c0	; ##      
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; Char : 0x5b [
; planes 0 and 1
.byte $f8,$f8	; #####   
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; planes 2 and 3
.byte $f8,$f8	; #####   
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $c0,$c0	; ##      
.byte $fe,$fe	; ####### 
.byte $00,$00	;         
; Char : 0x5c \
; planes 0 and 1
.byte $c0,$c0	; ##      
.byte $e0,$e0	; ###     
.byte $30,$30	;   ##    
.byte $18,$18	;    ##   
.byte $0c,$0c	;     ##  
.byte $06,$06	;      ## 
.byte $02,$02	;       # 
.byte $00,$00	;         
; planes 2 and 3
.byte $c0,$c0	; ##      
.byte $e0,$e0	; ###     
.byte $30,$30	;   ##    
.byte $18,$18	;    ##   
.byte $0c,$0c	;     ##  
.byte $06,$06	;      ## 
.byte $02,$02	;       # 
.byte $00,$00	;         
; Char : 0x5d ]
; planes 0 and 1
.byte $1e,$1e	;    #### 
.byte $02,$02	;       # 
.byte $02,$02	;       # 
.byte $02,$02	;       # 
.byte $02,$02	;       # 
.byte $02,$02	;       # 
.byte $1e,$1e	;    #### 
.byte $00,$00	;         
; planes 2 and 3
.byte $1e,$1e	;    #### 
.byte $02,$02	;       # 
.byte $02,$02	;       # 
.byte $02,$02	;       # 
.byte $02,$02	;       # 
.byte $02,$02	;       # 
.byte $1e,$1e	;    #### 
.byte $00,$00	;         
; Char : 0x5e ^
; planes 0 and 1
.byte $10,$10	;    #    
.byte $28,$28	;   # #   
.byte $44,$44	;  #   #  
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
; planes 2 and 3
.byte $10,$10	;    #    
.byte $28,$28	;   # #   
.byte $44,$44	;  #   #  
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
; Char : 0x5f _
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $ff,$ff	; ########
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $ff,$ff	; ########
.byte $00,$00	;         
; Char : 0x60 `
; planes 0 and 1
.byte $08,$08	;     #   
.byte $04,$04	;      #  
.byte $02,$02	;       # 
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
; planes 2 and 3
.byte $08,$08	;     #   
.byte $04,$04	;      #  
.byte $02,$02	;       # 
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
; Char : 0x61 a
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $04,$04	;      #  
.byte $7c,$7c	;  #####  
.byte $44,$44	;  #   #  
.byte $7e,$7e	;  ###### 
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $04,$04	;      #  
.byte $7c,$7c	;  #####  
.byte $44,$44	;  #   #  
.byte $7e,$7e	;  ###### 
.byte $00,$00	;         
; Char : 0x62 b
; planes 0 and 1
.byte $c0,$c0	; ##      
.byte $40,$40	;  #      
.byte $40,$40	;  #      
.byte $7c,$7c	;  #####  
.byte $44,$44	;  #   #  
.byte $44,$44	;  #   #  
.byte $fc,$fc	; ######  
.byte $00,$00	;         
; planes 2 and 3
.byte $c0,$c0	; ##      
.byte $40,$40	;  #      
.byte $40,$40	;  #      
.byte $7c,$7c	;  #####  
.byte $44,$44	;  #   #  
.byte $44,$44	;  #   #  
.byte $fc,$fc	; ######  
.byte $00,$00	;         
; Char : 0x63 c
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $40,$40	;  #      
.byte $40,$40	;  #      
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $40,$40	;  #      
.byte $40,$40	;  #      
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
; Char : 0x64 d
; planes 0 and 1
.byte $06,$06	;      ## 
.byte $04,$04	;      #  
.byte $04,$04	;      #  
.byte $7c,$7c	;  #####  
.byte $44,$44	;  #   #  
.byte $44,$44	;  #   #  
.byte $7e,$7e	;  ###### 
.byte $00,$00	;         
; planes 2 and 3
.byte $06,$06	;      ## 
.byte $04,$04	;      #  
.byte $04,$04	;      #  
.byte $7c,$7c	;  #####  
.byte $44,$44	;  #   #  
.byte $44,$44	;  #   #  
.byte $7e,$7e	;  ###### 
.byte $00,$00	;         
; Char : 0x65 e
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $44,$44	;  #   #  
.byte $7c,$7c	;  #####  
.byte $40,$40	;  #      
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $44,$44	;  #   #  
.byte $7c,$7c	;  #####  
.byte $40,$40	;  #      
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
; Char : 0x66 f
; planes 0 and 1
.byte $10,$10	;    #    
.byte $28,$28	;   # #   
.byte $20,$20	;   #     
.byte $70,$70	;  ###    
.byte $20,$20	;   #     
.byte $20,$20	;   #     
.byte $70,$70	;  ###    
.byte $00,$00	;         
; planes 2 and 3
.byte $10,$10	;    #    
.byte $28,$28	;   # #   
.byte $20,$20	;   #     
.byte $70,$70	;  ###    
.byte $20,$20	;   #     
.byte $20,$20	;   #     
.byte $70,$70	;  ###    
.byte $00,$00	;         
; Char : 0x67 g
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $04,$04	;      #  
.byte $7c,$7c	;  #####  
.byte $44,$44	;  #   #  
.byte $7c,$7c	;  #####  
.byte $04,$04	;      #  
.byte $7c,$7c	;  #####  
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $04,$04	;      #  
.byte $7c,$7c	;  #####  
.byte $44,$44	;  #   #  
.byte $7c,$7c	;  #####  
.byte $04,$04	;      #  
.byte $7c,$7c	;  #####  
; Char : 0x68 h
; planes 0 and 1
.byte $e0,$e0	; ###     
.byte $40,$40	;  #      
.byte $40,$40	;  #      
.byte $7c,$7c	;  #####  
.byte $44,$44	;  #   #  
.byte $44,$44	;  #   #  
.byte $ee,$ee	; ### ### 
.byte $00,$00	;         
; planes 2 and 3
.byte $e0,$e0	; ###     
.byte $40,$40	;  #      
.byte $40,$40	;  #      
.byte $7c,$7c	;  #####  
.byte $44,$44	;  #   #  
.byte $44,$44	;  #   #  
.byte $ee,$ee	; ### ### 
.byte $00,$00	;         
; Char : 0x69 i
; planes 0 and 1
.byte $00,$00	;         
.byte $10,$10	;    #    
.byte $00,$00	;         
.byte $30,$30	;   ##    
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $78,$78	;  ####   
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $10,$10	;    #    
.byte $00,$00	;         
.byte $30,$30	;   ##    
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $78,$78	;  ####   
.byte $00,$00	;         
; Char : 0x6a j
; planes 0 and 1
.byte $00,$00	;         
.byte $04,$04	;      #  
.byte $00,$00	;         
.byte $0c,$0c	;     ##  
.byte $04,$04	;      #  
.byte $04,$04	;      #  
.byte $44,$44	;  #   #  
.byte $3c,$3c	;   ####  
; planes 2 and 3
.byte $00,$00	;         
.byte $04,$04	;      #  
.byte $00,$00	;         
.byte $0c,$0c	;     ##  
.byte $04,$04	;      #  
.byte $04,$04	;      #  
.byte $44,$44	;  #   #  
.byte $3c,$3c	;   ####  
; Char : 0x6b k
; planes 0 and 1
.byte $c0,$c0	; ##      
.byte $40,$40	;  #      
.byte $40,$40	;  #      
.byte $58,$58	;  # ##   
.byte $60,$60	;  ##     
.byte $50,$50	;  # #    
.byte $48,$48	;  #  #   
.byte $00,$00	;         
; planes 2 and 3
.byte $c0,$c0	; ##      
.byte $40,$40	;  #      
.byte $40,$40	;  #      
.byte $58,$58	;  # ##   
.byte $60,$60	;  ##     
.byte $50,$50	;  # #    
.byte $48,$48	;  #  #   
.byte $00,$00	;         
; Char : 0x6c l
; planes 0 and 1
.byte $30,$30	;   ##    
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $78,$78	;  ####   
.byte $00,$00	;         
; planes 2 and 3
.byte $30,$30	;   ##    
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $78,$78	;  ####   
.byte $00,$00	;         
; Char : 0x6d m
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $e8,$e8	; ### #   
.byte $54,$54	;  # # #  
.byte $54,$54	;  # # #  
.byte $54,$54	;  # # #  
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $e8,$e8	; ### #   
.byte $54,$54	;  # # #  
.byte $54,$54	;  # # #  
.byte $54,$54	;  # # #  
.byte $00,$00	;         
; Char : 0x6e n
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $f0,$f0	; ####    
.byte $48,$48	;  #  #   
.byte $48,$48	;  #  #   
.byte $48,$48	;  #  #   
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $f0,$f0	; ####    
.byte $48,$48	;  #  #   
.byte $48,$48	;  #  #   
.byte $48,$48	;  #  #   
.byte $00,$00	;         
; Char : 0x6f o
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $44,$44	;  #   #  
.byte $44,$44	;  #   #  
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $44,$44	;  #   #  
.byte $44,$44	;  #   #  
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
; Char : 0x70 p
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $fc,$fc	; ######  
.byte $44,$44	;  #   #  
.byte $7c,$7c	;  #####  
.byte $40,$40	;  #      
.byte $e0,$e0	; ###     
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $fc,$fc	; ######  
.byte $44,$44	;  #   #  
.byte $7c,$7c	;  #####  
.byte $40,$40	;  #      
.byte $e0,$e0	; ###     
; Char : 0x71 q
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7e,$7e	;  ###### 
.byte $44,$44	;  #   #  
.byte $7c,$7c	;  #####  
.byte $04,$04	;      #  
.byte $0e,$0e	;     ### 
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7e,$7e	;  ###### 
.byte $44,$44	;  #   #  
.byte $7c,$7c	;  #####  
.byte $04,$04	;      #  
.byte $0e,$0e	;     ### 
; Char : 0x72 r
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $28,$28	;   # #   
.byte $34,$34	;   ## #  
.byte $20,$20	;   #     
.byte $70,$70	;  ###    
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $28,$28	;   # #   
.byte $34,$34	;   ## #  
.byte $20,$20	;   #     
.byte $70,$70	;  ###    
.byte $00,$00	;         
; Char : 0x73 s
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $40,$40	;  #      
.byte $7c,$7c	;  #####  
.byte $04,$04	;      #  
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $40,$40	;  #      
.byte $7c,$7c	;  #####  
.byte $04,$04	;      #  
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
; Char : 0x74 t
; planes 0 and 1
.byte $00,$00	;         
.byte $20,$20	;   #     
.byte $70,$70	;  ###    
.byte $20,$20	;   #     
.byte $20,$20	;   #     
.byte $28,$28	;   # #   
.byte $38,$38	;   ###   
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $20,$20	;   #     
.byte $70,$70	;  ###    
.byte $20,$20	;   #     
.byte $20,$20	;   #     
.byte $28,$28	;   # #   
.byte $38,$38	;   ###   
.byte $00,$00	;         
; Char : 0x75 u
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $c8,$c8	; ##  #   
.byte $48,$48	;  #  #   
.byte $48,$48	;  #  #   
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $c8,$c8	; ##  #   
.byte $48,$48	;  #  #   
.byte $48,$48	;  #  #   
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
; Char : 0x76 v
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $44,$44	;  #   #  
.byte $44,$44	;  #   #  
.byte $28,$28	;   # #   
.byte $10,$10	;    #    
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $44,$44	;  #   #  
.byte $44,$44	;  #   #  
.byte $28,$28	;   # #   
.byte $10,$10	;    #    
.byte $00,$00	;         
; Char : 0x77 w
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $42,$42	;  #    # 
.byte $42,$42	;  #    # 
.byte $5a,$5a	;  # ## # 
.byte $66,$66	;  ##  ## 
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $42,$42	;  #    # 
.byte $42,$42	;  #    # 
.byte $5a,$5a	;  # ## # 
.byte $66,$66	;  ##  ## 
.byte $00,$00	;         
; Char : 0x78 x
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $66,$66	;  ##  ## 
.byte $34,$34	;   ## #  
.byte $18,$18	;    ##   
.byte $34,$34	;   ## #  
.byte $66,$66	;  ##  ## 
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $66,$66	;  ##  ## 
.byte $34,$34	;   ## #  
.byte $18,$18	;    ##   
.byte $34,$34	;   ## #  
.byte $66,$66	;  ##  ## 
.byte $00,$00	;         
; Char : 0x79 y
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $44,$44	;  #   #  
.byte $44,$44	;  #   #  
.byte $7c,$7c	;  #####  
.byte $04,$04	;      #  
.byte $7c,$7c	;  #####  
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $44,$44	;  #   #  
.byte $44,$44	;  #   #  
.byte $7c,$7c	;  #####  
.byte $04,$04	;      #  
.byte $7c,$7c	;  #####  
; Char : 0x7a z
; planes 0 and 1
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $08,$08	;     #   
.byte $10,$10	;    #    
.byte $20,$20	;   #     
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $00,$00	;         
.byte $7c,$7c	;  #####  
.byte $08,$08	;     #   
.byte $10,$10	;    #    
.byte $20,$20	;   #     
.byte $7c,$7c	;  #####  
.byte $00,$00	;         
; Char : 0x7b {
; planes 0 and 1
.byte $30,$30	;   ##    
.byte $20,$20	;   #     
.byte $20,$20	;   #     
.byte $40,$40	;  #      
.byte $20,$20	;   #     
.byte $20,$20	;   #     
.byte $30,$30	;   ##    
.byte $00,$00	;         
; planes 2 and 3
.byte $30,$30	;   ##    
.byte $20,$20	;   #     
.byte $20,$20	;   #     
.byte $40,$40	;  #      
.byte $20,$20	;   #     
.byte $20,$20	;   #     
.byte $30,$30	;   ##    
.byte $00,$00	;         
; Char : 0x7c |
; planes 0 and 1
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $00,$00	;         
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $00,$00	;         
; planes 2 and 3
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $00,$00	;         
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $10,$10	;    #    
.byte $00,$00	;         
; Char : 0x7d }
; planes 0 and 1
.byte $18,$18	;    ##   
.byte $08,$08	;     #   
.byte $08,$08	;     #   
.byte $04,$04	;      #  
.byte $08,$08	;     #   
.byte $08,$08	;     #   
.byte $18,$18	;    ##   
.byte $00,$00	;         
; planes 2 and 3
.byte $18,$18	;    ##   
.byte $08,$08	;     #   
.byte $08,$08	;     #   
.byte $04,$04	;      #  
.byte $08,$08	;     #   
.byte $08,$08	;     #   
.byte $18,$18	;    ##   
.byte $00,$00	;         
; Char : 0x7e ~
; planes 0 and 1
.byte $3a,$3a	;   ### # 
.byte $6c,$6c	;  ## ##  
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
; planes 2 and 3
.byte $3a,$3a	;   ### # 
.byte $6c,$6c	;  ## ##  
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
.byte $00,$00	;         
; Char : 0x7f
; planes 0 and 1
.byte $00,$00	;         
.byte $54,$54	;  # # #  
.byte $2a,$2a	;   # # # 
.byte $54,$54	;  # # #  
.byte $2a,$2a	;   # # # 
.byte $54,$54	;  # # #  
.byte $2a,$2a	;   # # # 
.byte $00,$00	;         
; planes 2 and 3
.byte $00,$00	;         
.byte $54,$54	;  # # #  
.byte $2a,$2a	;   # # # 
.byte $54,$54	;  # # #  
.byte $2a,$2a	;   # # # 
.byte $54,$54	;  # # #  
.byte $2a,$2a	;   # # # 
.byte $00,$00	;         
